# Generated by Django 5.1.7 on 2025-03-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=60)),
                ('image', models.ImageField(blank=True, null=True, upload_to='employee_images/')),
                ('department', models.CharField(max_length=25)),
                ('salary', models.DecimalField(decimal_places=4, max_digits=10)),
                ('joined_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
